In [1]:
#Importing required libraries
import pandas as pd
import numpy as np
import datetime as dt

# Q1
## a. Group the DataFrame by 'Department' and calculate the mean salary for each department.

In [2]:
data = {'EmployeeID': [101, 102, 103, 104, 105],
         'EmployeeName': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
         'Department': ['HR', 'IT', 'HR', 'Finance', 'IT'],
         'Salary': [60000, 80000, 70000, 90000, 85000],
         'JoiningDate':[dt.date(2018, 5, 15), dt.date(2019, 2, 10), dt.date(2018, 8, 22), dt.date(2020, 1, 5), dt.date(2019, 7, 12)]}

In [3]:
df=pd.DataFrame(data)
df1=df.copy()

In [4]:
df1

EmployeeID EmployeeName Department  Salary JoiningDate
0         101        Alice         HR   60000  2018-05-15
1         102          Bob         IT   80000  2019-02-10
2         103      Charlie         HR   70000  2018-08-22
3         104        David    Finance   90000  2020-01-05
4         105          Eva         IT   85000  2019-07-12

In [5]:
df1.groupby("Department")[["Salary"]].mean()

Salary
Department         
Finance     90000.0
HR          65000.0
IT          82500.0

# Insights:
- Average Salary of Finance department is 90000.0
- Average Salary of HR department is 65000.0
- Average Salary of IT department is 82500.0

## b.Group the DataFrame by 'Department' and get the group with the highest average salary

In [6]:
df1.groupby("Department")[["Salary"]].mean()

Salary
Department         
Finance     90000.0
HR          65000.0
IT          82500.0

In [7]:
df1.groupby("Department")[["Salary"]].mean().max()

Salary    90000.0
dtype: float64

# Insights:
- Finance department has the highest Average Salary compared to other departments.

# Q2.
## a.Group the DataFrame by 'Department' and create a new DataFrame that shows the count of employees in each department.

In [8]:
df1.groupby("Department")[["EmployeeName"]].count()

EmployeeName
Department              
Finance                1
HR                     2
IT                     2

# Insights:
- Finance department has 1 Employee.
- HR department has 2 Employees.
- IT department has 2 Employees.

## b.Create a new column 'YearsInCompany' that calculates the number of years each employee has been with the company. Group the DataFrame by 'Department' and get the group with the employee who has been with the company for the longest time.

In [9]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   EmployeeID    5 non-null      int64 
 1   EmployeeName  5 non-null      object
 2   Department    5 non-null      object
 3   Salary        5 non-null      int64 
 4   JoiningDate   5 non-null      object
dtypes: int64(2), object(3)
memory usage: 328.0+ bytes


In [10]:
df1["JoiningDate"]=pd.to_datetime(df1["JoiningDate"])

In [11]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   EmployeeID    5 non-null      int64         
 1   EmployeeName  5 non-null      object        
 2   Department    5 non-null      object        
 3   Salary        5 non-null      int64         
 4   JoiningDate   5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 328.0+ bytes


In [12]:
df1["JoiningDate"].dt.year

0    2018
1    2019
2    2018
3    2020
4    2019
Name: JoiningDate, dtype: int64

In [13]:
pd.to_datetime("today").date()

datetime.date(2024, 4, 1)

In [14]:
df1["YearsInCompany"]=pd.to_datetime("today").year-df1["JoiningDate"].dt.year
df1

EmployeeID EmployeeName Department  Salary JoiningDate  YearsInCompany
0         101        Alice         HR   60000  2018-05-15               6
1         102          Bob         IT   80000  2019-02-10               5
2         103      Charlie         HR   70000  2018-08-22               6
3         104        David    Finance   90000  2020-01-05               4
4         105          Eva         IT   85000  2019-07-12               5

In [18]:
df1.groupby("Department")["EmployeeName","YearsInCompany"].max()

C:\Users\RAGHAVENDRA KUMAR\AppData\Local\Temp\ipykernel_25380\2923498679.py:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df1.groupby("Department")["EmployeeName","YearsInCompany"].max()


EmployeeName  YearsInCompany
Department                             
Finance           David               4
HR              Charlie               6
IT                  Eva               5

# Q3.
## a.Create a new column 'Bonus' that calculates a bonus of 15% of the salary for each employee. Group the DataFrame by 'Department' and find the department with the highest average bonus.


In [21]:
df1["Bonus"]=(df1["Salary"]*15)/100
df1

EmployeeID EmployeeName Department  Salary JoiningDate  YearsInCompany  \
0         101        Alice         HR   60000  2018-05-15               6   
1         102          Bob         IT   80000  2019-02-10               5   
2         103      Charlie         HR   70000  2018-08-22               6   
3         104        David    Finance   90000  2020-01-05               4   
4         105          Eva         IT   85000  2019-07-12               5   

     Bonus  
0   9000.0  
1  12000.0  
2  10500.0  
3  13500.0  
4  12750.0

In [23]:
df1.groupby("Department")[["Bonus"]].mean()

Bonus
Department         
Finance     13500.0
HR           9750.0
IT          12375.0

In [24]:
df1.groupby("Department")[["Bonus"]].mean().max()

Bonus    13500.0
dtype: float64

# Insights:
- Finance Department has highest Avearge Bonus compared to other Departments.

## b.Group the DataFrame by 'Department' and get the group with the employee who joined the company earliest in each department.


In [33]:
df1.groupby("Department")[["EmployeeName","JoiningDate"]].min()

EmployeeName JoiningDate
Department                         
Finance           David  2020-01-05
HR                Alice  2018-05-15
IT                  Bob  2019-02-10

# Insights:
- David was the earliest joined Employee in the Finance department.
- Alice was the earliest joined Employee in the HR department.
- Bob was the earliest joined Employee in the IT department.